server:
  port: 4000
spring:
  datasource:
    url: jdbc:mysql://192.168.99.101:3306/test
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect